folders:
  parent_dir: "./results/"
  model_name: "sr6_256x6_das_nc"

settings:
  game_id: "doapp"
  characters: "Kasumi"
  difficulty: 3
  step_ratio: 6
  frame_shape: !!python/tuple [256, 256, 1]
  continue_game: 0.0
  action_space: "discrete"
  attack_but_combination: false
  char_outfits: 2
  player: "Random"
  show_final: false

wrappers_settings:
  frame_stack: 6
  dilation: 1
  actions_stack: 12
  reward_normalization: true
  scale: true

custom_wrappers: false

key_to_add: ["actions", "ownHealth", "oppHealth", "ownSide", "oppSide", "stage"]

policy_kwargs:
  n_add_info: 161 # n_actions_stack*(n_actions[0]+n_actions[1]) + len(key_to_add)-1
  layers: [64, 64]

use_small_cnn: false

ppo_settings:
  gamma: 0.94
  model_checkpoint: "0M"
  learning_rate: [2.5e-4, 2.5e-6] # To start
  cliprange: [0.15, 0.025] # To start
  #learning_rate: [5.0e-5, 2.5e-6] # Fine Tuning
  #cliprange: [0.075, 0.025] # Fine Tuning
  nminibatches: 8
  noptepochs: 4
  n_steps: 128
  autosave_freq: 256
  time_steps: 512
