folders:
  parent_dir: "./selfplay_results/"
  model_name: "sr6_128x4_das_c"

settings:
  game_id: "doapp"
  characters: [["Kasumi"], ["Kasumi"]] # To be converted in tuple of tuples
  step_ratio: 6
  frame_shape: !!python/tuple [128, 128, 1]
  action_space: !!python/tuple ["discrete", "discrete"]
  attack_but_combination: !!python/tuple [true, true]
  char_outfits: !!python/tuple [2, 2]
  player: "P1P2"

wrappers_settings:
  frame_stack: 4
  dilation: 1
  actions_stack: 12
  reward_normalization: true
  scale: true

custom_wrappers: false

key_to_add:
  [
    "actions",
    "ownHealth",
    "oppHealth",
    "ownSide",
    "oppSide",
    "ownChar",
    "oppChar",
  ]

policy_kwargs:
  n_add_info: 230 # n_actions_stack*(n_actions[0]+n_actions[1]) + len(key_to_add)-3 + 2*nChars
  layers: [64, 64]

use_small_cnn: true

ppo_settings:
  gamma: 0.94
  model_checkpoint: "0M"
  learning_rate: [2.5e-4, 2.5e-6]
  cliprange: [0.15, 0.025]
  nminibatches: 8
  noptepochs: 4
  n_steps: 128
  autosave_freq: 256
  time_steps: 512

selfplay_settings:
  sampling_probability: 0.3
  previous_models: ["0M"]
  check_freq: 128
