folders:
  parent_dir: "./results/"
  model_name: "sr2_128x4_das_nc"

settings:
  game_id: "umk3"
  characters: ("Sektor")
  difficulty: 4
  step_ratio: 2
  frame_shape: (128, 128, 1)
  continue_game: 0.0
  action_space: "discrete"
  attack_but_combination: false
  char_outfits: 2
  player: "Random"
  show_final: false

wrappers_settings:
  frame_stack: 4
  dilation: 3
  actions_stack: 36
  reward_normalization: true
  scale: true

custom_wrappers: false

key_to_add: ["actions", "ownHealth", "oppHealth", "ownSide", "oppSide", "stage"]

policy_kwargs:
  n_add_info: 581 # n_actions_stack*(n_actions[0]+n_actions[1]) + len(key_to_add)-1
  layers: [64, 64]

use_small_cnn: true

ppo_settings:
  gamma: 0.9933
  model_checkpoint: "0M"
  learning_rate: [0.4e-4, 0.6e-6] # To start
  cliprange: [0.45, 0.075] # To start
  #learning_rate: [0.4e-5, 0.6e-6] # Fine Tuning
  #cliprange: [0.15, 0.025] # Fine Tuning
  nminibatches: 8
  noptepochs: 3
  n_steps: 384
  autosave_freq: 256
  time_steps: 512
