folders:
  parent_dir: "./results/"
  model_name: "sr6_128x4_das_nc"

settings:
  game_id: "tektagt"
  step_ratio: 6
  frame_shape: !!python/tuple [128, 128, 1]
  continue_game: 0.0
  action_space: "discrete"
  characters: !!python/tuple ["Jin", "Yoshimitsu"]
  difficulty: 6
  outfits: 2

wrappers_settings:
  normalize_reward: true
  no_attack_buttons_combinations: true
  stack_frames: 4
  add_last_action: true
  stack_actions: 12
  scale: true
  role_relative: true
  flatten: true

ram_states: ["action_move", "action_attack", "own_health_1", "own_health_2", "opp_health_1",
             "opp_health_2", "own_side", "opp_side", "own_active_character", "opp_active_character", "stage"]

policy_kwargs:
  n_add_info: 189 # n_actions_stack*(n_actions[0]+n_actions[1]) + len(key_to_add)-1
  layers: [64, 64]

use_small_cnn: true

ppo_settings:
  gamma: 0.94
  model_checkpoint: "0"
  learning_rate: [2.5e-4, 2.5e-6] # To start
  cliprange: [0.15, 0.025] # To start
  #learning_rate: [5.0e-5, 2.5e-6] # Fine Tuning
  #cliprange: [0.075, 0.025] # Fine Tuning
  nminibatches: 8
  noptepochs: 4
  n_steps: 128
  autosave_freq: 256
  time_steps: 512
