name: build-and-push

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  generate-matrix:
    name: Generate build matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Get changed files
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: changed-files
        with:
          dir_names: "true"
          since_last_remote_commit: "true"
        uses: tj-actions/changed-files@v29.0.2
      - id: set-matrix
        run: |
          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]]; then
            echo "::set-output name=matrix::$(./.github/workflows/generate-image-build-matrix ${{ steps.changed-files.outputs.all_changed_files }})"
          else
            echo "::set-output name=matrix::$(./.github/workflows/generate-image-build-matrix basic/* *)"
          fi
  build-and-push-images:
    needs: [generate-matrix]
    runs-on: ubuntu-latest
    if: ${{ needs.generate-matrix.outputs.matrix != '[]' }}
    strategy:
      fail-fast: true
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: diambrabot
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: diambra+github
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push agent ${{ matrix.dir }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.dir }}
          push: true
          tags: |
            ghcr.io/diambra/agent-${{ matrix.name }}:${{ github.sha }}
            ghcr.io/diambra/agent-${{ matrix.name }}:${{ github.head_ref || github.ref_name }}
            ${{ github.ref_name == 'main' && 'ghcr.io/diambra/agent-${{ matrix.name }}:latest' || '' }}

            docker.io/diambra/agent-${{ matrix.name }}:${{ github.sha }}
            docker.io/diambra/agent-${{ matrix.name }}:${{ github.head_ref || github.ref_name }}
            ${{ github.ref_name == 'main' && 'docker.io/diambra/agent-${{ matrix.name }}:latest' || '' }}

            quay.io/diambra/agent-${{ matrix.name }}:${{ github.sha }}
            quay.io/diambra/agent-${{ matrix.name }}:${{ github.head_ref || github.ref_name }}
            ${{ github.ref_name == 'main' && 'quay.io/diambra/agent-${{ matrix.name }}:latest' || '' }}
