name: Pull requests tests

on:
  pull_request: {}


jobs:
  test-package:
    name: Test using arena package
    uses: ./.github/workflows/reusable_unit_tests.yaml
    with:
      agents_ref: ${{ github.ref }}
  test-main:
    name: Test using arena main branch
    uses: ./.github/workflows/reusable_unit_tests.yaml
    with:
      arena_requirement_specifier: 'git+https://github.com/diambra/arena.git@main#egg='
      agents_ref: ${{ github.ref }}
